### ISSUE TITLE
66 Предприятие

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#11]
Немного поправить пикап кассы, он куда-то явно съехал не туда.

![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/2bcb0183-68ab-40c7-8e22-94174ada1021)
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/d7fd6aa1-c158-4b89-a031-f30167dfe7cd)

**Comment by taichi61** [comment]
@ViceMellan

**Comment by Hottab06** [comment]
@Blutertwo владелец бизнеса сам может настраивать положение пикапа кассы. Являюсь владельцем прачки, знаю не понаслышке. Закрываю тему.
