### ISSUE TITLE
Оружие

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#13]
Заходишь в магазин оружия, подходишь к тиру. Нажимешь для начала на прыжок, а после на Альт. У тебя выскакивает менюшка выбора оружия. Выбираешь любой ган и ты можешь с ним дальше разгуливать.
[https://www.youtube.com/watch?v=D02cSaH21rA](url) Также я вот ушёл в АФК, вышел, при этом всё же система кикнула и написались строчки. Попрошу также обратить внимание что написалось после красной.

![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/a0610bb2-ee2e-4c37-8e76-872a4da71743)

**Comment by taichi61** [comment]
Было исправлено.

**Comment by Blutertwo** [comment]
Работает исправно.
