### ISSUE TITLE
Ломбард

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#14]
Пишешь команду /bpanel в самом бизнесе. Выбираешь пункт управления мебелью. Выбираешь любой пункт без дальнейшего нажатия на кнопку выбора. Нажимаешь назад, однако у тебя возвращается не на предыдущую страницу, а идёт дальше (продолжение). Подробно будет видно на фрапсе. [https://www.youtube.com/watch?v=-ZPNcKxHmPc](url)

**Comment by taichi61** [comment]
Будет исправлено с рестартом.

**Comment by Blutertwo** [comment]
Работает корректно пункт который был указан, однако появился совершенно иной баг. Подробнее будет показано в ролике. При нажатие на кнопку "Открытие списка купленной мебели" и при выходе тебя перекидывает на меню жилья, а не предприятия. Также работает и с другой кнопкой. Также прошу обратить внимание на чат. [https://www.youtube.com/watch?v=clvKDXa7jQc](url)

**Comment by taichi61** [comment]
Тоже исправлено.

**Comment by Blutertwo** [comment]
Работает исправно
