### ISSUE TITLE
NYPD

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#15]
1. Нельзя игрока посадить в транспортное средство своего служебного автомобиля. Игрок обязательно должен быть в наручниках, после вводишь команду /incar id игрока и его автоматически ссадит в машину служебную именно на задние пассажирские места если таковы предусмотрены. Если все задние места заняты, то кто пишет данную команду будет писаться в чат (все задние пассажирские места заняты или же нет свободных мест). Данную команду можно использовать находясь рядом с крузером (служебным автомобилем), не обязательно находиться внутри него. Чтобы вывести игрока из автомобиля достаточно прописать команду /eject id
2. Сделать систему, что когда ведёшь игрока за собой при помощи команды /followme и переходишь из одного участка интерьера в другой, то игрока ТПхало автоматически. Приведу пример, ты приезжаешь к станции ПД, вытаскиваешь его из машины, прописываешь команду /followme и ведёшь его к пикапу входа. Ты сам заходишь в интерьер, а игрок же пока самостоятельно не нажмёт Alt не зайдёт в него, с чем могут быть некие казусы.
3. Добавить возможность лидеру с типом фракции "Полиция" и "Правительство" создавать фракционный эвакуатор 525 ид машины стандартный. Дабы те уже могли увозить транспорт на штрафстоянку.
4. Штрафстоянку необходимо пометить в /gps, а то я её там не нашёл и соответственно где она находится довольно проблематично.
5. Дать возможность даже обычным игрокам показывать свои лицензии другим (/showlic), а у копов должно это отображаться в /mdc. Тобишь когда пробиваешь игрока по /mdc помимо того, что у него можно отследить банковские транзиции и штрафы дать возможность проверить лицензии игрока какие у него есть и до какого они числа у него действительны.
6. Выдача штрафов на машину. Когда пробиваешь информацию по номерам машины, сделать возможность наложение на него штрафа. Если игрок был не в сети, на его аккаунт пришло бы уведомление в чат, что его транспортное средство было оштрафовано таким то сотрудником, на столько то денег и марка машины и его ид.
7. Дать возможность игрокам государственных организаций у которых предусмотрено использование команды /m, то её можно было бы использовать не только внутри крузера, но и находят вблизости того. А также добавить возможно использовать команду /ms, которая предназначена использование мегафона вне зависимости от использования рядом с крузером. Можно конечно упростить задачу и сделать просто /m без закрепления за транспортным средством.

**Comment by Blutertwo** [comment]
8. Криво работает команда /followme и /stayhere. Подробнее будет видно на фрапсе. [https://www.youtube.com/watch?v=GZTLJYlJ7Sc](url)

**Comment by taichi61** [comment]
/followme и /stayhere теперь работают корректно.
В /mdc добавлена информация о лицензиях персонажа.
Добавлена команда /incar.
Штрафстоянка давно отмечена в /gps.
Транспорт можно добавить самостоятельно.

Под остальное, пожалуйста, сделай новые тикеты.

**Comment by Blutertwo** [comment]
/followme багается. Прописываешь /followme, да игрок идёт за тобой, потом прописываешь /stayhere, но заного прописать /followme не удаётся, пишется в чат, мол я уже кого-то тащу за собой.
/incar попросту не работает, в том плане, что в машину нельзая посадить игрока, пробовал и на двухдверке и на четырёхдверке, никуда не садится парень.
В остальном всё исправлено. Фрапс подгружу позже.

**Comment by Blutertwo** [comment]
[https://www.youtube.com/watch?v=FwmOY0ckS1s](url)

**Comment by str41f** [comment]
Протестировано на 1.5.0. - Всё работает стабильно.
Всё работает исправно.
