### ISSUE TITLE
Рем.комплекты.

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#16]
На записи будет показано. Изуродовал машину до 480 ДЛ, использовать ремкомплект мне не даёт на машину. [https://www.youtube.com/watch?v=yQ1Bhd7tySs](url)

**Comment by taichi61** [comment]
Будет исправлено с рестартом.

**Comment by stpuIITu3ep** [comment]
Все еще актуально, даже при 900хп не позволяет использовать рем.комплект.

**Comment by taichi61** [comment]
Исправлено.

**Comment by Hottab06** [comment]
Исправлено, но ошибка некорректная.
Напишите, что, мол, хп автомобиля больше положенного, а то исходный вариант дезинформирует немного.

![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150608894/7a0134c2-7e4b-4411-89ec-60a510df8d39)

**Comment by taichi61** [comment]
Будет исправлено с рестартом.

**Comment by Hottab06** [comment]
Я так понял, оно предложенную надпись теперь так пишет на любой подходящий айдишник автомобиля, даже если его нет рядом или вообще в мире. Пусть будет ещё одно условие для этой надписи: если рядом нет данного автомобиля, то пусть пишет, мол, неверный айди, а в остальном всё работает как надо.

**Comment by Blutertwo** [comment]
С надписью уже давайте как улучшению. Не считаю багом
