### ISSUE TITLE
Скин

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#17]
Скины в игре не совпадают со скинами в личном кабинете. Поскольку были залиты заменки на старые скины или же просто сменили ИД, то у игроков в ЛК и в самой игре отличаются. 

![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/f4f09e95-6453-4aa1-9255-a40c12404b2d)
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/214df440-a8af-45d6-8782-86293447b545)

**Comment by taichi61** [comment]
Скинами занимаются сейчас.
