### ISSUE TITLE
Рация

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#20]
При увольнении с организации (на примере взял ПД) то можно просматривать рацию организации. Сделать так, чтоб при увольнении с фракции канал автоматически слетал и на него нельзя было зайти если ты гражданский.

**Comment by stpuIITu3ep** [comment]
Я же надеюсь речь идет про /f?

**Comment by Blutertwo** [comment]
Нет, про /r

**Comment by taichi61** [comment]
Будет исправлено с рестартом.

**Comment by Hottab06** [comment]
Да, исправлено, но у этой системы более серьёзная проблема.

Пусть пока здесь висит, опишу её позже.

**Comment by Hottab06** [comment]
В данный момент при кике с фракции настройки рации сбиваются в любом случае, но ведь игрок может находиться на волне, допустим, своих друзей, и эти настройки всё равно сбросит. Поэтому, пусть при кике с фракции настройки рации сбрасываются лишь в случае если у игрока установлена одна из следующих волн:

192 - СМИ
521 - Правительство
911 - ПД
912 - ФД

**Comment by Blutertwo** [comment]
Отправляется как предложение по улучшению
