### ISSUE TITLE
Оружие при кике

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#21]
При выходе, краше или кике игрока с сервера у госников пропадает оружие из активного слота и из инвентаря вприндцыпе. Нужно сделать сохранение оружия на 5 минут. Тобишь если игрок не зайдёт в течении этих 5-ти минут он будет снят с дежурства, у него пропадёт скин и табельное.

**Comment by taichi61** [comment]
В данный момент не представляется возможным, придётся переписывать большую часть системы инвентаря. Нет ничего сложного в том, чтобы рядом с машиной прописать /fdress и заново взять вооружение.

**Comment by Blutertwo** [comment]
Принято. /fdress работает исправно
