### ISSUE TITLE
Оружие в стадии

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#23]
У игрока в активном слоте оружие, он его использовал, его кинули в стадию, он принял ПК (отправился в морг), он в морге активно может использовать ган и когда его выпускаешь через команду /unmorgue у него также остаётся ган, при этом когда смотришь его интвентарь через /checkoffinv у него этого гана нет.

**Comment by Blutertwo** [comment]
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/3cf5bdd5-f220-4d23-985a-046d08ab380d)
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/73be093e-1a38-4843-b8e6-c09b66cb43ab)
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/a230d6e4-1411-4ea8-938d-7bd3b8899b95)
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/802f801d-b981-434c-89f2-701e8e827ce3)

**Comment by Blutertwo** [comment]
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/d3cfec95-07ef-414a-96b7-d22521b95bb3)

**Comment by Blutertwo** [comment]
![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/150464245/82e8f346-d2bc-4b4d-aacd-5d5a48a95c69)

**Comment by taichi61** [comment]
Необходимо видеодоказательство сюда, так сложно понять корень проблемы.

**Comment by cranley228** [comment]
Андрей Максимов - игрок ПД, у него фракционное оружие в руках, оно в чекоффинф не отображается.

**Comment by cranley228** [comment]
Проверял с фракционным оружием НУПД, АР15 не фракционный:
https://www.youtube.com/watch?v=6W1hwQdByag

**Comment by cranley228** [comment]
Само фракционное оружие очень криво работает, если пострелять из него и  перемести его из активного слота обратно в инвентарь, патроны пополняются к изначальному кол-во.



![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/155835363/a4773609-5caa-4fa3-ad98-729077a7ae11)



![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/155835363/4d45ac79-4dcb-4451-811e-948f6e710c08)



![Image](https://github.com/NEW-YORK-TIMES-Developers/.github/assets/155835363/7cc95433-8655-43c8-bed1-7aa1fb592fe7)

**Comment by thedruxxx** [comment]
также пример работы бага с непрогрузом убирания оружия. если в спеке человек уберёт оружие с активного слота - будет видимость того, что оружие у игрока до сих пор в руках

**Comment by str41f** [comment]
На тестовом данного бага нет. Протестировано.
