### ISSUE TITLE
9-1-1

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#24]
Переработать систему. Игроки жалуются, что не удобно когда один игрок принимает вызов, ты ждёшь пока он приедет на него и кинет /bk. Предлагаю немного переделать систему, а именно на данный вызов может реагировать 5-ть сотрудников. И как только 5-й сотрудник его принимает он удаляется. Также добавить сокращение принятия вызова. Каждый вызов имеет свой номер, соответственно чтоб в чат писался что был вызов под таким-то номером и игрок мог его быстро принять путём /acceptcall номер вызов.

**Comment by taichi61** [comment]
del

**Comment by taichi61** [comment]
Реализовано.

**Comment by Blutertwo** [comment]
Вопрос задам в личке ТГ по данному поводу. Система работает исправно
