### ISSUE TITLE
СМИ

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#25]
[https://www.youtube.com/watch?v=sRjVc9DtNto](url)

**Comment by taichi61** [comment]
Будет исправлено с рестартом.

**Comment by Blutertwo** [comment]
Баг остался

**Comment by Blutertwo** [comment]
Работает. Но при создании раздевалки появляется две надписи "[Раздевалка #0]" и "[Раздвелка #35]" (35 - это как пример, номер может быть другой в зависимости от созданного пикапа). При удалении этой самой 35-й раздевалки пикап удаляется, надпись удаляется, но остаётся Раздевалка 0. Функционировать если не удаётся с этой раздевалкой 0. Тобишь нужно убрать только надпись. [https://www.youtube.com/watch?v=-T5wbPEXAoo](url)

**Comment by taichi61** [comment]
Будет исправлено с рестартом.

**Comment by Blutertwo** [comment]
Работает исправно
