### ISSUE TITLE
Интерактивные объекты

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#26]
Не работают интерактивные объекты что у владельца, что у подселённого жильца. Выставляешь их, нажимаешь рядом с ними H, а они не работают. [https://www.youtube.com/watch?v=74xa4RUiTc8](url)

**Comment by taichi61** [comment]
Залью потенциальный фикс на тестовый сервер в ближайшее время.

**Comment by Blutertwo** [comment]
Работает исправно

**Comment by Blutertwo** [comment]
Персонально в дома 1234 почему-то не работает. У меня на основном в доме 19 работает, на тестовом покупал дом премиум класса (другой номер 475) тоже работает интерактивные объекты.

**Comment by taichi61** [comment]
Были некоторые манипуляции с интерактивными объектами, писал об этом в похожем тикете. Необходимо проверить ещё раз.

**Comment by timurtrionitov** [comment]
https://youtu.be/13tSNDoBNX0

При взаимодействии никакой реакции.

**Comment by taichi61** [comment]
Проблема была исправлена.

**Comment by str41f** [comment]
Перестали реагировать на H.

https://youtu.be/wA4vPHVHZqI

**Comment by thedruxxx** [comment]
на тестовом сервере не обнаружено неполадок, на h работает

**Comment by txtxtxtx16** [comment]
H срабатывает, но при взаимодействии 0 реакции

**Comment by EnforcementOfficer** [comment]
Вернулся баг...
https://forum.nytimes-gta.com/threads/interaktivnye-obekty.2373/
