### ISSUE TITLE
Телефонные разговоры в машине

### ISSUE THREAD

**Issue by Blutertwo** [NEW-YORK-TIMES-Developers/.github#28]
Когда сидишь в машине и разговариваешь по телефону, но при этом окна у тебя закрыты игроки что стоят на улице слышат твой диалог. [https://forum.nytimes-gta.com/threads/telefonnye-razgovory-slyshny-iz-mashiny.710/](url)

**Comment by taichi61** [comment]
Исправлено на тестовом сервере.

**Comment by rodnoysrt** [comment]
Исправлено на основе, все работает корректно.
